services:
  - type: web
    name: generator-nastavnih-priprema
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
